services:
  node-server:
    build:
      context: ./src/node-server
    networks:
      - backend
    expose:
      - "3000"
    depends_on:
      - mysql

  python-server:
    build:
      context: ./src/python-server
    networks:
      - backend
    expose:
      - "5000"
    depends_on:
      - mysql
      - node-server

  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - backend
    expose:
      - "3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./config/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mysql
      - node-server
      - python-server

networks:
  backend:
    driver: bridge
